엔티티 파일 생성을 완료했습니다!
yeonod/NestJsBasic pull request #15
Opened 2023-11-27 15:07 UTC by yeonod

## Background(배경지식)
작성한 ERD를 바탕으로 엔티티 파일 생성을 완료했습니다.
아직 외래키 추가는 하지 않았습니다.

## Implementations(보충설명)

## Screenshots (Optional)

## Focus On (Optional)

![image](https://github.com/yeonod/NestJsBasic/assets/104813592/abe02de9-2db2-4bd0-b644-b67c1d437cd5)
상품 테이블을 예시로 예제 코드를 작성 부탁드립니다.

## Other (Optional)

## References (Optional)

2023-11-27 17:11 UTC, kakasoo requested changes
변경 후 직접 merge 하고 새 PR에 새 수정사항들을 보내주세요. 지금 승인한 내용들은 다 끝난 게 아니지만 추후 전체 ERD를 보고 한 번 더 검토하겠습니다. 외래키 거는 법은 나머지 칼럼 검수가 모두 끝난 이후에 가르쳐드리겠습니다.

2023-11-27 17:11 UTC, kakasoo commented on src/entities/cart-input-option.entity.ts
> +export class CartInputOptionEntity extends CommonEntity {
입력옵션에는 무엇을 입력하라는건지에 대한 "주제"와 "힌트" 칼럼이 있어야 합니다.

2023-11-27 17:11 UTC, kakasoo commented on src/entities/cart-input-option.entity.ts
> +    cartRequiredId!: number;
int는 2의 32승이고 bigint는 2의 64승인 걸로 압니다. 여기서 length 20으로 한 기준은 뭔가요? 잘 모르신다면 default 값으로 지정하는 것도 나쁘지 않을 거에요.

2023-11-27 17:11 UTC, kakasoo commented on src/entities/cart.entity.ts
> +    count!: number;
칼럼마다 count에 대한 length가 다 다릅니다. 사실 count는 저 정도의 크기가 나올 수가 없을 텐데요 선택한 판단 근거가 궁금하고 왜 테이블마다 다른지도 의문입니다.

2023-11-27 17:11 UTC, kakasoo commented on src/entities/cart.entity.ts
> +    count!: number;
카트에 숫자가 있고 카트 옵션에도 숫자가 있다면 둘 중 어느 숫자를 믿어야하나요? 유저가 물건을 N개 담았다의 N는 카트인가요 카트 옵션인가요?

2023-11-27 17:11 UTC, kakasoo commented on src/entities/order-product-input-option.entity.ts
> +    count!: number;
맥북 3개에 각인은 3개만 가능하겠죠? 입력 옵션인데 수량이 있다면 그 수량은 무얼 의미하나요?

2023-11-27 17:11 UTC, kakasoo commented on src/entities/order-product-required-option.entity.ts
> +    name!: string;
다른 name 필드도 이미 지나쳤는지 모르겠습니다만, 128자는 상품 옵션 및 상품 이름으로는 너무 짧습니다.

2023-11-27 17:11 UTC, kakasoo commented on src/entities/order-product.entity.ts
> +    orderBundle!: number;
orderBundleId 말하는 거겠죠?

2023-11-27 17:11 UTC, kakasoo commented on src/entities/order.entity.ts
> +    id2!: number;
이게 뭐에요?

2023-11-27 17:11 UTC, kakasoo commented on src/entities/order-product-input-option.entity.ts
> +    value!: string;
값만 적지말고 상품의 입력 옵션에 있던 주제와 설명도 복사해서 가져와야 합니다. 입력 옵션이 수정되면 상품 입력 옵션은 다 꼬일 테니까, 그 당시의 입력 옵션 주제가 뭔지 기록해둬야 해요.

2023-11-27 17:11 UTC, kakasoo commented on src/entities/product-input-option.entity.ts
> +    value!: string;
name과 value의 차이가 뭔가요? 각각 무얼 의미하는 프로퍼티일까요?

2023-11-27 17:11 UTC, kakasoo commented on src/entities/product-option.entity.ts
> +    status!: string;
number 타입입니다. 또는 숫자를 직접 지정한 타입을 만들어주세요.

2023-11-27 17:11 UTC, kakasoo commented on src/entities/product-option.entity.ts
> +    status!: string;
숫자 리터럴 타입을 말한 겁니다.

2023-11-28 02:52 UTC, yeonod commented on src/entities/cart-input-option.entity.ts
> +export class CartInputOptionEntity extends CommonEntity {
예시를 통해 설명해주실 수 있을까요?

2023-11-28 02:54 UTC, yeonod commented on src/entities/cart-input-option.entity.ts
> +    cartRequiredId!: number;
프로젝트 단계이기 때문에 bigint로 작성한 컬럼들을 unsigned int로 변경하겠습니다.
(https://reasontaek.tistory.com/13 참조)

2023-11-28 02:56 UTC, yeonod commented on src/entities/product-option.entity.ts
> +    status!: string;
수정했습니다.

2023-11-28 03:01 UTC, yeonod commented on src/entities/product-input-option.entity.ts
> +    value!: string;
name은 입력 옵션 명, value는 해당 입력 옵션이 가지는 값을 의미합니다.

2023-11-28 03:02 UTC, yeonod commented on src/entities/order.entity.ts
> +    id2!: number;
유저id 외래키 값입니다. userId로 칼럼명 수정했습니다.

2023-11-28 03:40 UTC, yeonod commented on src/entities/order-product.entity.ts
> +    orderBundle!: number;
수정했습니다.

2023-11-28 03:40 UTC, yeonod commented on src/entities/order-product-required-option.entity.ts
> +    name!: string;
몇 자 정도 사용하는 것이 적당할까요?

2023-11-28 03:42 UTC, kakasoo commented on src/entities/cart-input-option.entity.ts
> +export class CartInputOptionEntity extends CommonEntity {
예를 들어 각인 옵션이 있다면 "각인"과 "홍길동" 같은 값들이 있어야 사용자들이 입력 가능하겠죠? 장바구니의 입력 옵션에도 이런 정보가 옮겨져야 합니다.

2023-11-28 03:42 UTC, kakasoo commented on src/entities/product-input-option.entity.ts
> +    value!: string;
value가 예시라는 걸까요? 상품의 입력 옵션에 value를 가진다는 게 무슨 의미인지 잘 이해가 안됩니다.

2023-11-28 05:42 UTC, kakasoo commented on src/entities/order-product-required-option.entity.ts
> +    name!: string;
정책마다 다르겠지만 수백자는 넘을 수도 있습니다.

2023-11-28 13:26 UTC, yeonod commented on src/entities/cart.entity.ts
> +    count!: number;
카드의 count는 물건 개수, 카트 옵션의 count는 옵션 개수로 생각하고 만들었는데, 옵션 개수가 늘어나면 옵션 엔티티 자체의 개수가 증가하므로 이 부분은 카트 옵션의 count 칼럼을 삭제하는 방향으로 수정하겠습니다.

2023-11-28 13:34 UTC, yeonod commented on src/entities/order-product-input-option.entity.ts
> +    count!: number;
입력 옵션에 해당하는 엔티티들의 count 칼럼을 삭제했습니다.

2023-11-28 13:36 UTC, yeonod commented
리뷰 주신 사항 중 수정 필요한 부분 수정해서 merge 했습니다.
반영되지 않은 부분은 다음 PR로 넘겨서 질문 드리겠습니다.

2023-11-28 13:36 UTC, merged

2023-11-28 14:33 UTC, yeonod commented on src/entities/cart-input-option.entity.ts
> +export class CartInputOptionEntity extends CommonEntity {
추가했습니다.